width='100%';		// the width of the embedded map in pixels or percentage
height='450';		// the height of the embedded map in pixels or percentage
border='1';		// the width of the border around the map (zero means no border)
shownames='true';	// to display ship names on the map (true or false)
// latitude='37.4460';	// the latitude of the center of the map, in decimal degrees
// longitude='24.9467';	// the longitude of the center of the map, in decimal degrees
zoom='16';		// the zoom level of the map (values between 2 and 17)
maptype='3';		// use 0 for Normal map, 1 for Satellite, 2 for Hybrid, 3 for Terrain
// trackvessel='563717000';	// MMSI of a vessel (note: vessel will be displayed only if within range of the system) - overrides "zoom" option
fleet='vlad_1984@list.ru';		// the registered email address of a user-defined fleet (user's default fleet is used)
remember='false';	// remember or not the last position of the map (true or false)
language='ru';		// the preferred display language
showmenu=false;		// show or hide the map options menu